#服务暴露顿口号
server:
  port: 8091
#服务名称
spring:
  application:
    name: lee-gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          #启用基于服务发现的路由定位
          enabled: true
          #启用服务实例id名称小写支持
          lower-case-service-id: true
      default-filters:
        -name: Hystrix
        args:
          name: hystrixError
          fallbackUri: forward:/error
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8099}/eureka/
  instance:
    #优先使用IP地址注册
    prefer-ip-address: true
    ##服务所属分组名称
    app-group-name: lee_group
    #服务实例id
management:
  endpoint:
    conditions:
      enabled: true