server:
  port: 8099
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
    registerWithEureka: false
    fetchRegistry: false
spring:
  application:
    name: lee-eurekaserver
  security:
    basic:
      enabled: false
    user:
      name: usernameLee
      password: passwordLee
